# Compiler definitions
CXX      = g++
CXXFLAGS = -c -Wall $(addprefix -D,$(DEFINES)) -I$(INCLUDE_DIR) $(MAKEFILE_DEPS_FLAGS) -std=c++11
MAKEFILE_DEPS_FLAGS = -MMD -MP
DEFINES  = 
LDFLAGS  =

# Helper programs
MKDIR_P = mkdir -p

# Directories
SOURCE_DIR = src
INCLUDE_DIR = include
OBJ_DEBUG = obj_debug
OBJ_RELEASE = obj_release
BIN_DEBUG = bin_debug
BIN_RELEASE = bin_release

# Files
EXECUTABLE = $(BIN_DIR)/archipelego
INCLUDES = $(wildcard $(INCLUDE_DIR)/*.h)
SOURCES = $(wildcard $(SOURCE_DIR)/*.cpp)
OBJECTS = $(SOURCES:$(SOURCE_DIR)/%.cpp=$(OBJ_DIR)/%.o)
DEPS = $(OBJECTS:.o=.d)

# Debug definitions
ifdef DEBUG
DEFINES += DEBUG
TARGET = DEBUG
BIN_DIR = $(BIN_DEBUG)
OBJ_DIR = $(OBJ_DEBUG)
else
TARGET = RELEASE
BIN_DIR = $(BIN_RELEASE)
OBJ_DIR = $(OBJ_RELEASE)
endif

# Phony Targets
.PHONY: intro dirs all debug cleanall clean

all: intro dirs $(OBJECTS) $(EXECUTABLE)
	@echo "All done."

intro:
	@echo "Building sources for $(TARGET) target $(EXECUTABLE).\n"

clean:
	rm -rf $(OBJ_DIR) $(BIN_DIR)
	@echo "Cleaned $(TARGET)."

cleanall:
	rm -rf $(OBJ_DEBUG) $(BIN_DEBUG) $(OBJ_RELEASE) $(BIN_RELEASE)
	@echo "Cleaned all."

dirs: $(OBJ_DIR) $(BIN_DIR)

# Real Targets

$(EXECUTABLE): $(OBJECTS)
	@echo "Linking $(EXECUTABLE)..."
	$(CXX) $(LDFLAGS) $(OBJECTS) -o $(EXECUTABLE)
	@echo "Done.\n"

#TODO: can the pattern matching look nicer?
$(OBJ_DIR)/%.o: $(SOURCE_DIR)/%.cpp
	@echo "Compiling $< ..."
	$(CXX) $(CXXFLAGS)  $< -o $@
	@echo "Done.\n"

$(OBJ_DIR) $(BIN_DIR):	
	@echo "Creating output folder..."
	$(MKDIR_P) $@;
	@echo "Done.\n"
	
# Include dependency targets generated by (-MMD -MP) flags
-include $(DEPS)